<?php

declare(strict_types=1);

namespace FieldPulse\Storage;

use FieldPulse\Config\Config;
use FieldPulse\Database\SubmissionRepository;
use FieldPulse\Support\Logger;
use FieldPulse\Support\Paths;

/**
 * Crash-safe evidence placement.
 *
 * The problem this class exists to name
 * -------------------------------------
 * Ingestion writes bytes to the filesystem and rows to MySQL. Those are two
 * different kinds of store with no shared commit. MySQL will atomically roll
 * back an INSERT that fails; it cannot roll back a rename() that already
 * succeeded, and rename() cannot be enlisted in the transaction that would have
 * told anyone about it.
 *
 * So the honest options are: either find a single store and lose the other
 * one's guarantees, or make the order of operations such that every crash
 * leaves a state a reconciler can detect. This is the second option.
 *
 * Write order
 * -----------
 *   1. bytes land in quarantine/ and the destination is fsync'd
 *   2. the ledger row commits, recording QUARANTINED
 *   3. verification renames into processed/<disposition>/
 *   4. a single UPDATE rewrites file_path and sets PROCESSED
 *
 * Every crash window has a defined meaning:
 *
 *   between 1 and 2   an orphan file in quarantine/ with no row. Harmless and
 *                     detectable: no row references it, and bin/prune.php
 *                     deletes unreferenced quarantine files past a grace period.
 *                     The evidence is not lost, because no ledger claims it.
 *
 *   between 3 and 4   the bytes are in their final disposition folder but the row
 *                     still names quarantine/. Detectable, because the final
 *                     filename is deterministic from the submission UUID — so
 *                     reconcile() knows exactly where to look for it. This is the
 *                     one window that needs the naming scheme to be stable, and
 *                     that is why finalPath() exists rather than an inline
 *                     string concat at the call site.
 *
 *   never            a row in PROCESSED whose file is absent. That is storage
 *                     loss, not a race, and reconcile() records it as MISSING
 *                     rather than leaving the row lying.
 *
 * The guarantee this class makes is therefore not "no crash can lose evidence".
 * Nothing can promise that. It is: a crash is always *visible*, and the visible
 * state always names the next concrete action.
 */
final class StorageState
{
    private function __construct()
    {
    }

    /**
     * The final location for a submission, derived only from its UUID and MIME.
     *
     * Deterministic on purpose — see the class docblock. UUID is generated by
     * the server and validated as a UUID before it reaches here, and the
     * extension comes from the server-detected MIME rather than the client's
     * filename, so this cannot be steered into an arbitrary path.
     */
    public static function finalPath(string $submissionUuid, string $serverMime, string $disposition): string
    {
        $folder = match ($disposition) {
            SubmissionRepository::VERIFIED        => Paths::DIR_VERIFIED,
            SubmissionRepository::REQUIRES_REVIEW => Paths::DIR_REVIEW,
            default                             => Paths::DIR_REJECTED,
        };

        return $folder . '/' . $submissionUuid . '.' . self::extensionFor($serverMime);
    }

    /**
     * Move a verified submission into its disposition folder and record it.
     *
     * The rename happens first and the row is updated second. Reversing that
     * order would be worse, not better: a row pointing at processed/ before the
     * bytes arrive describes a file that does not exist yet, and a reader in
     * that window cannot tell the difference from one that never will. With
     * this order the intermediate state is "the file is in quarantine according
     * to the row, and also in processed/ according to the disk" — a duplicate
     * rather than a phantom, and reconcile() resolves it by hashing.
     *
     * @return bool True when the row and the bytes agree afterwards. False means
     *              the move did not happen and the caller should leave the job
     *              retryable rather than marking the submission terminal.
     */
    public static function archive(SubmissionRepository $submissions, array $submission, string $disposition): bool
    {
        $id   = (int) $submission['id'];
        $uuid = (string) $submission['submission_uuid'];
        $mime = (string) $submission['file_mime'];

        $relative = self::finalPath($uuid, $mime, $disposition);

        try {
            $source = Paths::absoluteForStoredPath((string) $submission['file_path']);
            $target = Paths::storagePath($relative);
        } catch (\Throwable $e) {
            // A path that will not validate is a bug or a tampered row, not a
            // transient condition. Retrying will not change the answer.
            Logger::error('storage.archive_path_invalid', [
                'submission_id' => $id,
                'error'         => $e->getMessage(),
            ]);

            return false;
        }

        // Already where it belongs: the row update is the only thing missing,
        // which is exactly the "crashed between 3 and 4" case above. Repair it
        // instead of reporting failure, because the bytes are correct.
        if (!is_file($source) && is_file($target)) {
            $submissions->markStorageMoved($id, $relative, SubmissionRepository::STORAGE_PROCESSED);

            Logger::warning('storage.archive_repaired', ['submission_id' => $id]);

            return true;
        }

        if (!is_file($source)) {
            Logger::warning('storage.archive_source_missing', ['submission_id' => $id]);

            return false;
        }

        if (!@rename($source, $target)) {
            Logger::error('storage.archive_move_failed', ['submission_id' => $id]);

            return false;
        }

        self::hardenFile($target);
        self::fsyncDir(dirname($target));

        $submissions->markStorageMoved($id, $relative, SubmissionRepository::STORAGE_PROCESSED);

        return true;
    }

    /**
     * Check that every non-terminal row's bytes are where the row says.
     *
     * Bounded and idempotent: safe to run from cron, safe to interrupt, and
     * safe to run twice. Reports rather than throws, because a reconciler that
     * dies on the first anomaly is a reconciler that never reaches the second.
     *
     * @return array{checked:int,missing:int,repaired:int,unreadable:int}
     */
    public static function reconcile(SubmissionRepository $submissions, int $limit = 500): array
    {
        $stats = ['checked' => 0, 'missing' => 0, 'repaired' => 0, 'unreadable' => 0];

        foreach ($submissions->rowsForStorageReconcile($limit) as $row) {
            $stats['checked']++;

            $id   = (int) $row['id'];
            $path = (string) $row['file_path'];

            try {
                $absolute = Paths::absoluteForStoredPath($path);
            } catch (\Throwable) {
                $stats['unreadable']++;
                continue;
            }

            if (is_file($absolute)) {
                continue;
            }

            /*
             * The recorded path is empty. Before calling that loss, look for the
             * bytes at every deterministic final location: a crash between
             * rename and row-update produces exactly this, and recovering it is
             * the whole reason finalPath() is deterministic.
             *
             * All three disposition folders are searched, not the one derived
             * from status, and the reason is the write order.
             *
             * archive() runs BEFORE the disposition is committed, so at the
             * moment of a crash the row still reads PROCESSING or QUEUED — the
             * verdict it was about to receive was never written. A reconciler
             * that trusted status would resolve the destination to REJECTED (the
             * default for anything it does not recognise), search
             * processed/rejected, find nothing, and record MISSING for evidence
             * that is sitting in processed/verified. That is the worst possible
             * outcome: a repairable state converted into a permanent record of
             * data loss, by the very code meant to prevent it.
             *
             * The filename does not depend on the disposition — it is the UUID
             * and the server-detected extension, identical in all three folders —
             * so searching each in turn is exact rather than a guess. A UUID
             * collision is not a concern: they are v4, and the lookup is keyed
             * on the row that owns the name.
             */
            $found = false;

            foreach (self::candidatePaths(
                (string) self::lookupUuid($submissions, $id),
                (string) $row['file_mime']
            ) as $candidate) {
                try {
                    $candidateAbsolute = Paths::absoluteForStoredPath($candidate);
                } catch (\Throwable) {
                    $stats['unreadable']++;
                    continue;
                }

                if (!is_file($candidateAbsolute)) {
                    continue;
                }

                $submissions->markStorageMoved($id, $candidate, SubmissionRepository::STORAGE_PROCESSED);
                $stats['repaired']++;

                Logger::warning('storage.reconcile_repaired', [
                    'submission_id' => $id,
                    'path'          => $candidate,
                ]);

                $found = true;
                break;
            }

            if ($found) {
                continue;
            }

            $submissions->markStorageMissing($id);
            $stats['missing']++;

            Logger::error('storage.reconcile_missing', ['submission_id' => $id]);
        }

        return $stats;
    }

    /**
     * 0640 on the file, matching storage.file_perms.
     *
     * A no-op on Windows, where ACLs are inherited from the parent directory
     * rather than expressed as mode bits. The call is suppressed and its result
     * ignored deliberately: a chmod that fails on a filesystem without POSIX
     * permissions is not a reason to reject evidence.
     */
    public static function hardenFile(string $absolute): void
    {
        @chmod($absolute, Config::instance()->int('storage.file_perms', 0640));
    }

    /**
     * fsync the directory so a completed rename survives power loss.
     *
     * rename() returning true means the rename happened in the page cache. On
     * an ext4 default (data=ordered) with a power cut immediately after, the
     * directory entry can still be lost. This is the difference between "the
     * move succeeded" and "the move is durable", and it costs one syscall on a
     * path that runs once per verified submission.
     *
     * Best-effort: some filesystems and Windows do not permit opening a
     * directory for this, and the failure is logged rather than raised because
     * refusing to accept evidence on a filesystem that cannot fsync a directory
     * would be a worse outcome than a rare lost directory entry.
     */
    public static function fsyncDir(string $absolute): void
    {
        if (PHP_OS_FAMILY === 'Windows') {
            return;
        }

        $handle = @fopen($absolute, 'r');

        if ($handle === false) {
            return;
        }

        if (!@fsync($handle)) {
            Logger::warning('storage.fsync_dir_unsupported', []);
        }

        fclose($handle);
    }

    private static function extensionFor(string $serverMime): string
    {
        // Only ever reached with a MIME that ImageInspector already validated
        // against storage.allowed_mimes, so the default branch is unreachable in
        // practice. It returns 'jpg' rather than throwing because an unreadable
        // row should be reconciled, not fatal.
        return $serverMime === 'image/png' ? 'png' : 'jpg';
    }

    /**
     * Every path the bytes for a submission could legitimately occupy.
     *
     * See reconcile() for why the disposition is not part of this. Ordered
     * VERIFIED, REQUIRES_REVIEW, REJECTED so a repaired row is deterministic if
     * more than one somehow exists — which would itself be worth investigating,
     * since it means the same UUID was archived twice.
     *
     * @return list<string>
     */
    private static function candidatePaths(string $submissionUuid, string $serverMime): array
    {
        if ($submissionUuid === '') {
            return [];
        }

        return [
            self::finalPath($submissionUuid, $serverMime, SubmissionRepository::VERIFIED),
            self::finalPath($submissionUuid, $serverMime, SubmissionRepository::REQUIRES_REVIEW),
            self::finalPath($submissionUuid, $serverMime, SubmissionRepository::REJECTED),
        ];
    }

    private static function lookupUuid(SubmissionRepository $submissions, int $id): string
    {
        $row = $submissions->findById($id);

        return (string) ($row['submission_uuid'] ?? '');
    }
}